// Code generated by "stringer -type=StreamEventType -output=stream_string.go"; DO NOT EDIT.

package llm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StreamEventTextDelta-0]
	_ = x[StreamEventToolUseStart-1]
	_ = x[StreamEventToolInputDelta-2]
	_ = x[StreamEventThinkingDelta-3]
	_ = x[StreamEventContentBlockStop-4]
	_ = x[StreamEventMessageComplete-5]
	_ = x[StreamEventRequestStart-6]
}

const _StreamEventType_name = "StreamEventTextDeltaStreamEventToolUseStartStreamEventToolInputDeltaStreamEventThinkingDeltaStreamEventContentBlockStopStreamEventMessageCompleteStreamEventRequestStart"

var _StreamEventType_index = [...]uint8{0, 20, 43, 68, 92, 119, 145, 168}

func (i StreamEventType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StreamEventType_index)-1 {
		return "StreamEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StreamEventType_name[_StreamEventType_index[idx]:_StreamEventType_index[idx+1]]
}
