// A command line tool for generating typescript type declarations from go
// struct types.
//
// Example:
//
//	go run ./cmd/go2ts -o ui/src/generated-types.ts
package main

import (
	"flag"
	"fmt"
	"os"
	"time"

	"go.skia.org/infra/go/go2ts"
	"shelley.exe.dev/db"
	"shelley.exe.dev/db/generated"
	"shelley.exe.dev/llm"
)

func main() {
	outputPath := flag.String("o", "", "Path to the output TypeScript file.")
	flag.Parse()

	if *outputPath == "" {
		fmt.Println("Usage: go run ./cmd/go2ts -o <output-file>")
		os.Exit(1)
	}

	generator := TS()

	w, err := os.Create(*outputPath)
	if err != nil {
		fmt.Printf("error: %v\n", err)
		os.Exit(1)
	}
	defer w.Close()

	fmt.Fprintf(w, "// Auto-generated by shelley.exe.dev/cmd/go2ts.go\n")
	fmt.Fprintf(w, "// Do not edit manually - regenerate with: go run ./cmd/go2ts -o ui/src/generated-types.ts\n\n")
	generator.Render(w)
}

// TS returns a Go2TS generator for go types we want to use in TypeScript.
func TS() *go2ts.Go2TS {
	generator := go2ts.New()

	// Database message types enum
	generator.AddMultipleUnion(
		[]db.MessageType{
			db.MessageTypeUser,
			db.MessageTypeAgent,
			db.MessageTypeTool,
			db.MessageTypeError,
			db.MessageTypeSystem,
			db.MessageTypeGitInfo,
		},
	)

	// Database struct types
	generator.AddMultiple(
		generated.Conversation{},
		llm.Usage{},
	)

	generator.AddMultiple(
		apiMessageForTS{},
		streamResponseForTS{},
	)

	// Generate clean nominal types
	generator.GenerateNominalTypes = true

	return generator
}

type apiMessageForTS struct {
	MessageID      string    `json:"message_id"`
	ConversationID string    `json:"conversation_id"`
	SequenceID     int64     `json:"sequence_id"`
	Type           string    `json:"type"`
	LlmData        *string   `json:"llm_data,omitempty"`
	UserData       *string   `json:"user_data,omitempty"`
	UsageData      *string   `json:"usage_data,omitempty"`
	CreatedAt      time.Time `json:"created_at"`
	DisplayData    *string   `json:"display_data,omitempty"`
	EndOfTurn      *bool     `json:"end_of_turn,omitempty"`
}

type streamResponseForTS struct {
	Messages     []apiMessageForTS      `json:"messages"`
	Conversation generated.Conversation `json:"conversation"`
	AgentWorking *bool                  `json:"agent_working,omitempty"`
}
